hyperskill_project:
  id: 335
  ide_files: https://hyperskill.org/api/projects/335/additional-files/additional_files.json
  is_template_based: false
  use_ide: true
  environment: android
update_date: "Sat, 05 Apr 2025 10:49:29 UTC"
stages:
  - id: 1877
    step: 27514
    is_completed: true
  - id: 1878
    step: 27515
    is_completed: true
  - id: 1879
    step: 27516
    is_completed: true
  - id: 1880
    step: 27517
    is_completed: true
  - id: 1881
    step: 27518
    is_completed: true
topics:
  0:
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: "Basic terms: JVM, JRE, JDK"
      theory_id: 3499
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Introduction to Jetpack Compose
      theory_id: 24814
    - title: Jetpack Compose Project Structure
      theory_id: 25491
    - title: "Hello, Compose!"
      theory_id: 24825
    - title: Introduction to Kotlin
      theory_id: 4350
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 4351
    - title: Writing first program
      theory_id: 4362
    - title: Values and variables
      theory_id: 4371
    - title: Constants and val variables
      theory_id: 17408
    - title: Data types
      theory_id: 4388
    - title: Comments
      theory_id: 4406
    - title: Kotlin style guide. Coding conventions
      theory_id: 4419
    - title: Naming variables
      theory_id: 4389
    - title: Standard output
      theory_id: 4425
    - title: Invoking functions
      theory_id: 4575
    - title: Standard input with Java Scanner
      theory_id: 4445
    - title: String basics
      theory_id: 12553
    - title: String templates
      theory_id: 4547
    - title: Boolean type and operations. True and false
      theory_id: 4515
    - title: Arithmetic operations
      theory_id: 4472
    - title: Increment and decrement
      theory_id: 10776
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Build tools
      theory_id: 4284
    - title: "Gradle: overview"
      theory_id: 5075
    - title: Properties of basic types
      theory_id: 4455
    - title: Type conversion
      theory_id: 4672
    - title: Reading data with readln
      theory_id: 11224
    - title: "When different types meet: type coercion"
      theory_id: 9506
    - title: Integers in action
      theory_id: 4488
    - title: Comparing numbers. Relational operators
      theory_id: 4525
    - title: Declaring functions
      theory_id: 4580
    - title: If expression
      theory_id: 4625
    - title: Errors in programs
      theory_id: 11559
    - title: "Loops: repeat statement"
      theory_id: 4643
    - title: Objects and their properties
      theory_id: 11233
    - title: Declaring classes
      theory_id: 6200
    - title: Structural vs referential equality
      theory_id: 11236
    - title: Work with MutableLists
      theory_id: 14902
    - title: Functions as objects
      theory_id: 5991
    - title: Lambda expressions
      theory_id: 30148
    - title: Unicode
      theory_id: 7899
    - title: Characters. Char type
      theory_id: 4680
    - title: Ranges
      theory_id: 4633
    - title: When expression
      theory_id: 4631
    - title: Functional decomposition
      theory_id: 12668
    - title: Default arguments
      theory_id: 4637
    - title: Named arguments
      theory_id: 4640
    - title: Constructors
      theory_id: 10740
    - title: Member functions
      theory_id: 6364
    - title: Working with strings
      theory_id: 12561
    - title: Introduction to collections
      theory_id: 10390
    - title: List
      theory_id: 10730
    - title: For loop and ranges
      theory_id: 4652
    - title: For loop and lists
      theory_id: 15022
    - title: Extension functions
      theory_id: 6621
    - title: External resources
      theory_id: 6216
    - title: Android studio basics
      theory_id: 11048
    - title: API Levels
      theory_id: 11312
    - title: Files
      theory_id: 13025
    - title: Reading files
      theory_id: 6351
    - title: Writing files
      theory_id: 9710
    - title: Introduction to Android
      theory_id: 6331
    - title: XML
      theory_id: 6901
    - title: Android Project Structure
      theory_id: 10752
    - title: AndroidManifest File
      theory_id: 10762
    - title: Resources
      theory_id: 11087
    - title: RGB
      theory_id: 8819
    - title: Image colors
      theory_id: 14484
    - title: Text Composable
      theory_id: 25502
    - title: Exception
      theory_id: 7243
    - title: Intro to annotations
      theory_id: 22296
  1:
    - title: Data structures
      theory_id: 40371
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: Stack
      theory_id: 5252
    - title: Nullable and non-nullable types
      theory_id: 7613
    - title: Type system
      theory_id: 9689
    - title: While loops
      theory_id: 4659
    - title: Function references
      theory_id: 15420
    - title: Concept of design patterns
      theory_id: 3611
    - title: Call stack
      theory_id: 11550
    - title: Scopes
      theory_id: 17116
    - title: Nested and inner classes
      theory_id: 14723
    - title: Getting substrings
      theory_id: 8535
    - title: Processing strings
      theory_id: 9027
    - title: Introduction to software architecture
      theory_id: 15368
    - title: Interfaces
      theory_id: 9640
    - title: Code organization. Design principles
      theory_id: 8956
    - title: Inheritance
      theory_id: 9844
    - title: Inheritance
      theory_id: 7770
    - title: Polymorphism
      theory_id: 10027
    - title: Overriding functions
      theory_id: 7884
    - title: Introduction to Interfaces
      theory_id: 18222
    - title: Single Responsibility Principle
      theory_id: 8963
    - title: Object declarations
      theory_id: 10698
    - title: Companion object
      theory_id: 10707
    - title: Regexps
      theory_id: 10721
    - title: "Sets, ranges, and alternations"
      theory_id: 14514
    - title: Quantifiers
      theory_id: 14567
    - title: Shorthands
      theory_id: 14540
    - title: Regexps in use
      theory_id: 14633
    - title: TextField Composable
      theory_id: 25634
    - title: "Column, Row and Box"
      theory_id: 25685
    - title: Hierarchy of exceptions
      theory_id: 13264
    - title: Taming exceptions
      theory_id: 7601
    - title: Avoiding NPEs. Null safety
      theory_id: 7619
    - title: Creational design patterns
      theory_id: 16251
    - title: Singleton
      theory_id: 16469
    - title: Regular expression
      theory_id: 7580
  2:
    - title: Recomposition
      theory_id: 28325
    - title: Compose State
      theory_id: 28475
    - title: Remember in Compose
      theory_id: 29515
    - title: Mutable List
      theory_id: 11032
    - title: Encapsulation
      theory_id: 8519
    - title: Property accessors
      theory_id: 10511
    - title: Introduction to generic programming
      theory_id: 14698
    - title: Generic functions
      theory_id: 16052
  4:
    - title: Introduction to UI/UX
      theory_id: 14603
    - title: Layout grids
      theory_id: 14922
    - title: Interface elements
      theory_id: 15253
    - title: Feedback
      theory_id: 15308
    - title: Toast
      theory_id: 11973
    - title: Modifying Composables
      theory_id: 38658
    - title: Buttons
      theory_id: 43128
